# Generated by Django 5.2 on 2025-04-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0003_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
