# Generated by Django 5.2 on 2025-05-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0004_booking_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
